extends:
  - airbnb-base
  - plugin:jest/recommended
  - prettier
plugins:
  - filenames
  - prettier
  - 'inclusive-language'
ignorePatterns:
  - lib/
  - lib/**/*
rules:
  filenames/match-regex: [2, '^[a-z0-9-.]+$', true]
  filenames/no-index: 2
  curly: ['error', 'all']
  prettier/prettier: ['error']
  indent: ['error', 4, { SwitchCase: 1 }]
  max-len: [1, 120]
parserOptions:
  ecmaVersion: 2020
