# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Install
        run: |
          npm i npm@latest -g
          npm ci
      - name: Lint
        run: npm run lint
      - name: Audit
        run: npm run audit
      - name: Test
        run: npm test
